spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0 # 개발 환경 100% 샘플링

auth-server:
  signing-key:
    source: database

logging:
  level:
    com.haenaryn.authserver: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
